routes/admin.php
<?php

Route::get('/home', 'AdminController@dashboard')->name('home');

Route::resource('user', 'Resource\UserResource');
Route::resource('helpcenter', 'HelpCenterResource');

Route::get('user/{id}/kycdoc', 'AdminController@kycdoc')->name('user.kycdoc');
Route::get('user/{id}/{status}', 'AdminController@userStatus')->name('user.userStatus');
Route::get('userapproval/{id}/{status}', 'AdminController@userApprovalStatus')->name('user.userApprovalStatus');
Route::get('{id}/details', 'Resource\UserResource@details')->name('details');
Route::get('{id}/walletdetails', 'AdminController@walletdetails')->name('walletdetails');
 

//Google 2 factor
Route::get('/Google2fa', function () {
  if(isset($_GET['google_succ'])){
        if($_GET['google_succ']==1){
          \Session::flash('flash_success',"Google two factor authentication enabled successfully...");
        }
    }
  return view('admin.2fa.google2factor');
});

Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor');
Route::get('/2fa/disable', 'Google2FAController@disableTwoFactor');
Route::post('/g2fotpcheckenable', 'Google2FAController@g2fotpcheckenable');

Route::get('/2fa/urlform', 'AdminController@getValidateToken');
Route::post('/2fa/urlvalidate', ['middleware' => 'throttle:5', 'uses' => 'AdminController@postValidateToken']);




Route::get('user/{id}/history', 'AdminController@transhistory')->name('user.history');
Route::get('user/{id}/edituserid', 'AdminController@edituserid')->name('user.edituserid');
Route::post('user/edituseridstore', 'AdminController@edituseridstore')->name('user.edituseridstore');

Route::get('user/{id}/coins', 'AdminController@coins')->name('user.coins');

Route::get('history', 'AdminController@history')->name('history');
Route::get('history/success/{id}', 'AdminController@historySuccess')->name('history.success');
Route::get('history/failed/{id}', 'AdminController@historyFailed')->name('history.failed');

Route::get('settings/index', 'AdminController@settings')->name('settings.index');
Route::post('settings/store', 'AdminController@settings_store')->name('settings.store');

Route::get('settings/payment', 'AdminController@settings_payment')->name('settings.payment');
Route::post('settings/payment', 'AdminController@settings_payment_store')->name('settings.payment.store');

Route::get('profile', 'AdminController@profile')->name('profile');
Route::post('profile', 'AdminController@profile_update')->name('profile.update');

Route::get('password', 'AdminController@password')->name('password');
Route::post('password', 'AdminController@password_update')->name('password.update');


//Tokenizer
Route::get('/tokenizerindex','TokenizerController@tokenizerindex')->name('tokenizerindex');
Route::get('/tokenizer','TokenizerController@tokenizer')->name('tokenizer');

Route::get('/tokenizeredit/{id}','TokenizerController@tokenizeredit')->name('tokenizeredit');
Route::post('/tokenizerupdate','TokenizerController@tokenizerupdate')->name('tokenizerupdate');

Route::get('/requestedtoken','TokenizerController@requestedtoken')->name('requestedtoken');
Route::get('/tokenhistory','TokenizerController@tokenhistory')->name('tokenhistory');
Route::get('/issuertokencontract/{id}','TokenizerController@issuertokencontract')->name('issuertokencontract');

Route::get('/issuertokencontracttest/{id}','TokenizerController@issuertokencontracttest')->name('issuertokencontracttest');
Route::get('/issuertokenreject/{id}','TokenizerController@issuertokenreject')->name('issuertokenreject');


Route::post('/contractcreate', 'TokenizerController@contractcreate')->name('contractcreate');
Route::post('/contract/update', 'TokenizerController@contractupdate')->name('contractupdate');


//User Token

Route::get('/usertoken/index','UserTokenController@index')->name('usertoken.index');
Route::get('/usertoken/usertransaction/{id}','UserTokenController@index')->name('usertoken.usertransaction');

Route::get('/usertoken/transaction','UserTokenController@tokentransaction')->name('usertoken.transaction');

Route::get('/usertoken/transactionstatus/{id}','UserTokenController@tokentransactionstatus')->name('usertoken.transactionstatus');

Route::get('/dividend','UserTokenController@dividend')->name('dividend');



//fiat History  
Route::get('fiatHistory', 'AdminController@fiatHistory')->name('fiatHistory');
Route::get('walletHistory', 'AdminController@walletHistory')->name('walletHistory');

Route::get('/translation',  'AdminController@translation')->name('translation');

//History
Route::get('history', 'AdminController@history')->name('history');

//Privacy
Route::get('/privacy', 'AdminController@privacy')->name('privacy');
Route::get('/wallet', 'AdminController@adminwallet')->name('adminwallet');
Route::post('/pages', 'AdminController@pages')->name('pages.update');

//Terms
Route::get('/terms', 'AdminController@terms')->name('terms');
Route::post('/termspage', 'AdminController@termspages')->name('terms.update');
Route::post('/privacypages', 'AdminController@privacypages')->name('privacy.update');

Route::get('/about', 'AdminController@about')->name('about');
Route::post('/aboutpages', 'AdminController@aboutpages')->name('about.update');

//Promocode
Route::resource('promocode', 'PromocodeResource');

//Token
Route::resource('token', 'TokenResource');
Route::get('/token/document/{id}', 'TokenResource@viewdocument')->name('token.document');
Route::post('/token/status', 'TokenResource@status');

//Document Resource
Route::resource('document', 'DocumentResource');
Route::resource('corpdocument', 'CorpDocumentResource');

//AccreditedDocument Resource
Route::resource('accrediteddocument', 'AccreditedDocumentResource');

//ProspectusDocument Resource
Route::resource('prospectusdocument', 'ProspectusDocumentResource');

//Coins Resource
Route::resource('coin', 'CoinResource');
Route::get('coin/{id}/enableStatus', 'CoinResource@enableStatus')->name('coin.enableStatus');
Route::get('coin/{id}/disableStatus', 'CoinResource@disableStatus')->name('coin.disableStatus');

Route::get('user/{id}/kycdoc', 'AdminController@kycdoc')->name('user.kycdoc');
Route::post('userdocument/approve', 'AdminController@userdocument_approve')->name('userdocument.approve');
Route::post('userdocument/reject', 'AdminController@userdocument_reject')->name('userdocument.reject');

Route::get('user/{id}/accrediteddoc', 'AdminController@accrediteddoc')->name('user.accrediteddoc');
Route::post('useraccrediteddocument/approve', 'AdminController@useraccrediteddocument_approve')->name('useraccrediteddocument.approve');
Route::post('useraccrediteddocument/reject', 'AdminController@useraccrediteddocument_reject')->name('useraccrediteddocument.reject');

Route::get('user/{id}/approve', 'AdminController@approve')->name('user.approve');
Route::get('user/{id}/disapprove', 'AdminController@disapprove')->name('user.disapprove');

//withdraw

Route::get('pendingwithdraw', 'AdminController@pendingwithdraw')->name('pendingwithdraw');

Route::get('allwithdraw', 'AdminController@allwithdraw')->name('allwithdraw');


//cryptopendingwithdraw

Route::get('cryptopendingwithdraw', 'AdminController@cryptopendingwithdraw')->name('cryptopendingwithdraw');

Route::get('cryptoallwithdraw', 'AdminController@cryptoallwithdraw')->name('cryptoallwithdraw');



Route::get('history/success/{id}', 'AdminController@historySuccess')->name('history.success');

Route::get('history/failed/{id}', 'AdminController@historyFailed')->name('history.failed');

Route::get('coinwithdrawhistory/success/{id}', 'AdminController@coinwithdrawhistorySuccess')->name('coinwithdrawhistory.success');

Route::get('coinwithdrawhistory/failed/{id}', 'AdminController@coinwithdrawhistoryFailed')->name('coinwithdrawhistory.failed');


Route::get('receivehistory/success/{id}', 'AdminController@ReceivehistorySuccess')->name('receivehistory.success');

Route::get('receivehistory/failed/{id}', 'AdminController@ReceivehistoryFailed')->name('receivehistory.failed');

Route::post('addwireamount', 'AdminController@addwireamount')->name('addwireamount');
Route::get('removewireamount/{id}', 'AdminController@removewireamount')->name('removewireamount');

//Edit coin

Route::post('editcoin', 'AdminController@editcoin')->name('editcoin');

Route::post('savecoin', 'AdminController@savecoin')->name('savecoin');

Route::get('/btcotpgenerate/{ctype}', 'AdminController@btcotpgenerate')->name('btcotpgenerate');


Route::post('overallBTC', 'AdminController@overallBTC')->name('overallBTC');
Route::post('overallLTC', 'AdminController@overallLTC')->name('overallLTC');
Route::post('overallBCH', 'AdminController@overallBCH')->name('overallBCH');
Route::post('withdrawETH', 'AdminController@withdrawETH')->name('withdrawETH');

Route::any('withETH', 'AdminController@withdrawETH');

Route::get('/support','AdminController@support')->name('support');
//supportdone
Route::get('/supportdone/{id}/{status}','AdminController@supportdone')->name('supportdone');

Route::get('/addtoken','AdminController@addtoken')->name('addtoken');
//addtokendone
Route::get('/addtokendone/{id}','AdminController@addtokendone')->name('addtokendone');


//Sub Admin

Route::get('/listsubadmin', 'AdminController@listsubadmin')->name('listsubadmin');
Route::get('/createsubadmin', 'AdminController@createsubadmin')->name('createsubadmin');
Route::get('/editsubadmin/{id}', 'AdminController@editsubadmin')->name('editsubadmin');
Route::post('/storesubadmin', 'AdminController@storesubadmin')->name('storesubadmin');
Route::post('/updatesubadmin', 'AdminController@updatesubadmin')->name('updatesubadmin');
Route::delete('/destroysubadmin/{id}', 'AdminController@destroysubadmin')->name('destroysubadmin');

//sendmailforkycrejection
Route::get('sendmailforkycrejection', 'AdminController@sendmailforkycrejection')->name('sendmailforkycrejection');
Route::get('kycmail', 'AdminController@kycmail')->name('kycmail');

// Voting 
Route::resource('vote', 'VoteController');
Route::get('vote/status/{id}', 'VoteController@status')->name('admin.vote.status');

routes/web.php
    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::get('/issuer/login', 'Auth\LoginController@showLoginIssuerForm')->name('adminIssuerlogin');
Route::post('/issuer/login', 'AdminAuth\LoginController@login');

Route::get('/issuer/register', 'Auth\RegisterController@showIssuerRegistrationForm')->name('Issuerregister');
Route::post('/issuer/register', 'Auth\RegisterController@register_issuer');



Route::get('/', 'Auth\LoginController@welcome');
Route::post('getenquiryform', 'Auth\LoginController@getenquiryform')->name('getenquiryform');
Route::post('getenquiryformhome', 'HomeController@getenquiryformhome')->name('getenquiryformhome');
Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify')->name('email_verify');

Route::get('forgot', function () {
    return view('forgot');
});

Route::get('/success', function () {
    return view('success');
});

Route::get('/wyre', 'WyreController@index');
Route::get('/wyretest', 'WyreController@wyretest');

Route::get('fiatpaymentstatus', 'WyreController@fiatpaymentstatus')->name('fiatpaymentstatus');

Auth::routes();

Route::get('/admin/dashboard', 'AdminDashboardController@index')->middleware('auth:admin');

Route::group(['middleware' => 'auth'], function () {
    // ********************** Investor ***********************
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@investment')->name('dashboard');
    //Route::get('/propertyList', 'HomeController@propertyList')->name('propertyList');
    Route::get('/intel', 'HomeController@intel')->name('intel');
     Route::get('/help', 'HomeController@help')->name('help');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::get('/propertyDetail/{id}', 'HomeController@propertyDetail')->name('propertyDetail');
    Route::get('/applyInvest/{id}', 'HomeController@applyInvest')->name('applyInvest');
    Route::post('investstore', 'HomeController@investstore')->name('investstore');


    Route::get('walletBalanceAPI', 'HomeController@wallet_balance_api')->name('walletBalanceAPI');


    Route::get('security', 'UserController@security')->name('security');

    Route::post('/change/password', 'HomeController@update_password')->name('change.password');
    Route::get('participants', function () {
        return view('participants');
    });
    Route::get('prospectus', 'HomeController@prospectus');
    Route::post('prospectus_download', 'HomeController@prospectus_download')->name('prospectus_download');
    Route::get('kyc', 'HomeController@kyc');
    Route::post('personalinfo', 'HomeController@personalinfo');
    Route::post('userdetail', 'HomeController@userdetail')->name('userdetail');
    Route::post('kycstore', 'HomeController@kycstore');
    Route::post('accrediteduserstore', 'HomeController@accrediteduserstore');
    Route::post('accreditedkycstore', 'HomeController@accreditedkycstore');
    Route::post('usercompanydetail', 'HomeController@usercompanydetail')->name('usercompanydetail');
    Route::post('usercompanypersonaldetail', 'HomeController@usercompanypersonaldetail')->name('usercompanypersonaldetail');
    Route::get('wallet', 'HomeController@wallet')->name('wallet');
    Route::get('payment_history', 'HomeController@paymenthistory')->name('paymenthistory');
    Route::get('withdrawETH', 'HomeController@withdrawETHBalance')->name('withdrawETH');
    Route::post('/sendETH', 'HomeController@sendETH')->name('sendETH');
    Route::get('/generate/withdrawOTP', 'HomeController@generateWithdrawOTP')->name('generateWithdrawOTP');
    Route::post('privateKeyPassword', 'HomeController@privateKeyPassword')->name('privateKeyPassword');
    Route::get('privateKeyShow/{id}', 'HomeController@privateKeyShow')->name('privateKeyShow');
    Route::post('requestaddress', 'HomeController@requestaddress')->name('requestaddress');
    Route::post('addtoken', 'HomeController@addtoken')->name('addtoken');
    Route::post('withdraw', 'HomeController@withdraw')->name('withdraw');
    Route::post('storePayment', 'HomeController@storePayment');

    Route::get('balance', 'HomeController@balance_of_coin')->name('balance');
    Route::post('getcryptobalance', 'HomeController@getcryptobalance')->name('getcryptobalance');
    Route::post('gettokeninvestvalue', 'HomeController@gettokeninvestvalue')->name('gettokeninvestvalue');
    

    // ---------------- Invest --------------------
    Route::get('invest_token/{id}', 'HomeController@invest_token')->name('invest_token');
    Route::post('investstore', 'HomeController@investstore')->name('investstore');
    //Route::get('fiatpaymentstatus', 'HomeController@fiatpaymentstatus')->name('fiatpaymentstatus');
    // ---------------- Invest -------------------  -

    Route::get('dividend', 'HomeController@dividend');
    Route::get('voting', 'HomeController@showvoting');
    Route::post('votingstore', 'HomeController@votingstore')->name('votingstore');
    Route::get('support', function () {
        return view('support');
    });
    Route::post('supportstore', 'HomeController@supportstore')->name('supportstore');

    Route::get('privacy-policy', function () {
        return view('privacy-policy');
    });
    Route::get('terms-use', function () {
        return view('terms-use');
    });
    // ********************** Investor ***********************

    //Google 2 factor
    Route::get('g2fenablesuccess/{id}', 'UserController@g2fenablesuccess')->name('g2fenablesuccess');
    Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor');
    Route::get('/2fa/disable', 'Google2FAController@disableTwoFactor')->name('disableTwoFactor');;
    // Web check otp
    Route::post('/g2fotpcheckenable', 'Google2FAController@g2fotpcheckenable');

});

Route::get('/2fa/validate', 'Auth\LoginController@getValidateToken');
Route::post('/2fa/validate', ['middleware' => 'throttle:5', 'uses' => 'Auth\LoginController@postValidateToken']);

// API check otp
//Route::post('/gfaenablereal', 'Google2FAController@postValidateToken');
Route::post('/gfavalidateotp', 'Google2FAController@gfavalidateotp');


/*Route Real Estate STO*/

Route::get('/privacy', function(){ return view('privacy');});
Route::get('/terms_conditions', function(){ return view('terms_conditions');});

Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('/blogDetail', 'HomeController@blogDetail')->name('blogDetail'); //Dynami
//Route::get('/wallet', 'HomeController@wallet')->name('wallet');
Route::get('/investment', 'HomeController@investment')->name('investment');
Route::get('/investDetail', 'HomeController@investDetail')->name('investDetail');
Route::get('/setting', 'HomeController@setting')->name('setting');
Route::get('/activity', 'HomeController@activity')->name('activity');
Route::get('/sellToken', 'HomeController@sellToken')->name('sellToken');
Route::get('/buyToken', 'HomeController@buyToken')->name('buyToken');
Route::post('/profile-identity', 'HomeController@profile_identity')->name('profile.identity');
Route::post('/phelp', 'HomeController@phelp')->name('phelp');
Route::post('/profile-finance', 'HomeController@profile_finance')->name('profile.finance');
Route::post('/profile-background', 'HomeController@profile_background')->name('profile.background');
Route::get('/propertyList', 'HomeController@propertyList')->name('propertyList');

Route::get('/under_construction', function () {
    return view('under_construction');
}
);

Route::get('/propertyList/{type?}', 'HomeController@propertyList')->name('propertyList');
Route::get('/property-asset-list/{type}', 'HomeController@propertyAssetList')->name('propertyAssetList');


Route::get('/propertyDetail/{id}', 'HomeController@propertyDetail')->name('propertyDetail'); // Dynamic

Route::get('/countrycity/{country}', 'UserController@countrycity')->name('countrycity');
Route::group(['prefix' => 'issuer', 'middleware' => 'auth'], function () {
    Route::get('/dashboard', 'IssuerController@dashboard')->name('dashboard');
    Route::get('/kyc', 'IssuerController@kyc')->name('kyc');
    Route::post('/kyc', 'IssuerController@updateKyc')->name('updateKyc');
     Route::post('/updateBankDetails', 'IssuerController@updateBankDetails')->name('updateBankDetails');
    Route::get('/profile', 'IssuerController@profile')->name('profile');
    Route::post('/profile_update', 'IssuerController@profile_update')->name('profile_update');
    Route::get('/property', 'IssuerController@property')->name('property');
    Route::post('/property', 'IssuerController@storeProperty')->name('propertyStore');
    Route::get('/withdrawETH', 'IssuerController@withdrawETHBalance')->name('withdrawETH');
    Route::post('/sendETH', 'IssuerController@sendETH')->name('sendETH');
    Route::get('/generate/withdrawOTP', 'IssuerController@generateWithdrawOTP')->name('generateWithdrawOTP');
    Route::get('/token', 'IssuerController@token')->name('token');
    Route::get('/asset_fund', 'IssuerController@asset_fund')->name('asset_fund');
    Route::get('/propertydetails/{id}', 'IssuerController@propertyDetail')->name('issuer_propertyDetail'); // Dynamic
    Route::get('/tokenList/{id}', 'IssuerController@tokenList')->name('tokenList');
    Route::get('/tokenRequest', 'IssuerController@tokenRequest')->name('tokenRequest');
    Route::get('/tokenApprove', 'IssuerController@tokenApprove')->name('tokenApprove');
    Route::get('/issuer_paymenthistory', 'IssuerController@wallet')->name('issuer_paymenthistory');
    Route::get('razorpay-payment', 'RazorpayController@index');

resources/views/admin/coins/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add cointype Type ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <a href="{{ route('admin.coin.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> Back</a>

            <h5 style="margin-bottom: 2em;">Add Coin</h5>

            <form class="form-horizontal" action="{{route('admin.coin.store')}}" method="POST" enctype="multipart/form-data" role="form">
                {{ csrf_field() }}

                <div class="form-group row">
                    <label for="name" class="col-xs-12 col-form-label">Coin Name</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" name="coin_name" required id="coin_name" placeholder="Coin Name">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="symbol" class="col-xs-12 col-form-label">Coin Symbol</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text"name="symbol" required id="symbol" placeholder="Coin Symbol">
                    </div>
                </div>

                {{-- <div class="form-group row">
                    <label class="col-xs-12 col-form-label">Coin Order</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="number" name="sort_order" required id="sort_order" placeholder="Coin Order">
                    </div>
                </div> --}}

                <div class="form-group row">
                    <label class="col-xs-12 col-form-label">Token or Not</label>
                    <div class="col-xs-10">
                        <input type="checkbox" name="coin_type" id="coin_type"/> Yes
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-xs-12 col-form-label">Contract Address</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" name="contract_address"  id="contract_address" placeholder="Contract Address">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-xs-12 col-form-label">Address</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" name="address"  id="address" placeholder="Address">
                    </div>
                </div>

                <div class="form-group">
                    <p class="alert alert-info col-xs-10"><b>Note:</b> Please check your address once and twice before submit...</p>
                </div>

                {{-- <div class="form-group row">
                    <label for="qr_code" class="col-xs-12 col-form-label">Coin Icon</label>
                    <div class="col-xs-10">
                        <input type="file" accept="image/*" name="image" class="form-control-file" id="image" aria-describedby="fileHelp">
                    </div>
                </div> --}}

               
                <div class="form-group row">
                    <div class="col-xs-10">
                        <div class="row">
                            <div class="col-xs-12 col-sm-6 col-md-3">
                                <a href="{{ route('admin.coin.index') }}" class="btn btn-danger btn-block">Cancel</a>
                            </div>
                            <div class="col-xs-12 col-sm-6 offset-md-6 col-md-3">
                                <button type="submit" class="btn btn-primary btn-block">Add Coin Type</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/admin/coins/index.blade.php
@extends('admin.layout.base')

@section('title', 'Coins ')

@section('content')
<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
         
            <!-- <a href="{{ route('admin.coin.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Add New Coin</a> -->
            <table class="table table-striped table-bordered dataTable" id="table-2">
                <thead>
                    <tr>
                       <th>Id</th>
                        <th>Coin Name</th>
                        <th>Coin Symbol</th>
                        <th>Coin Order</th>
                        <th>Coin Image</th>
                        <th>Type</th>
                        <th>Status</th>
                        <!-- <th>Action</th> -->
                    </tr>
                </thead>
                <tbody>
                    @foreach($Coin as $index => $coin)
                    <tr>
                        <td>{{ $index + 1 }}</td>
                        <td>{{ $coin->coin_name }}</td>
                        <td>{{ $coin->symbol }}</td>
                        <td>{{ $coin->sort_order }}</td>
                        <td>@if($coin->image !='')<center><img style="height: 30px; margin-bottom: 15px;"  src="{{ img($coin->image) }}" /></center>@endif</td>
                        
                        <td>    
                            @if($coin->coin_type == '1')
                             Token
                            @else
                             Coin
                            @endif  
                        </td>

                        <td>    
                            @if($coin->status == '1')
                            <a class="btn btn-danger btn-block" href="{{ route('admin.coin.disableStatus', $coin->id ) }}">@lang('Disable')</a>
                            @else
                            <a class="btn btn-success btn-block" href="{{ route('admin.coin.enableStatus', $coin->id ) }}">@lang('Enable')</a>
                            @endif  
                        </td>

                        <!-- <td>
                            <form action="{{ route('admin.coin.destroy', $coin->id) }}" method="POST">
                                {{ csrf_field() }}
                                <input type="hidden" name="_method" value="DELETE">
                               
                                <a href="{{ route('admin.coin.edit', $coin->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i>Edit</a>
                                <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i>Delete</button>
                                
                            </form>
                        </td> -->
                    </tr>
                    @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>ID</th>
                        <th>Coin Name</th>
                        <th>Coin Symbol</th>
                        <th>Coin Order</th>
                        <th>Type</th>
                        <th>Status</th>
                        <!-- <th>Action</th> -->
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection