routes/admin.php
Route::get('profile', 'AdminController@profile')->name('profile');
Route::post('profile', 'AdminController@profile_update')->name('profile.update');

Route::get('password', 'AdminController@password')->name('password');
Route::post('password', 'AdminController@password_update')->name('password.update');


//Tokenizer
Route::get('/tokenizerindex','TokenizerController@tokenizerindex')->name('tokenizerindex');
Route::get('/tokenizer','TokenizerController@tokenizer')->name('tokenizer');

Route::get('/tokenizeredit/{id}','TokenizerController@tokenizeredit')->name('tokenizeredit');
Route::post('/tokenizerupdate','TokenizerController@tokenizerupdate')->name('tokenizerupdate');

Route::get('/requestedtoken','TokenizerController@requestedtoken')->name('requestedtoken');
Route::get('/tokenhistory','TokenizerController@tokenhistory')->name('tokenhistory');
Route::get('/issuertokencontract/{id}','TokenizerController@issuertokencontract')->name('issuertokencontract');

Route::get('/issuertokencontracttest/{id}','TokenizerController@issuertokencontracttest')->name('issuertokencontracttest');
Route::get('/issuertokenreject/{id}','TokenizerController@issuertokenreject')->name('issuertokenreject');


Route::post('/contractcreate', 'TokenizerController@contractcreate')->name('contractcreate');
Route::post('/contract/update', 'TokenizerController@contractupdate')->name('contractupdate');


//User Token

Route::get('/usertoken/index','UserTokenController@index')->name('usertoken.index');
Route::get('/usertoken/usertransaction/{id}','UserTokenController@index')->name('usertoken.usertransaction');

Route::get('/usertoken/transaction','UserTokenController@tokentransaction')->name('usertoken.transaction');

Route::get('/usertoken/transactionstatus/{id}','UserTokenController@tokentransactionstatus')->name('usertoken.transactionstatus');

Route::get('/dividend','UserTokenController@dividend')->name('dividend');



//fiat History  
Route::get('fiatHistory', 'AdminController@fiatHistory')->name('fiatHistory');
Route::get('walletHistory', 'AdminController@walletHistory')->name('walletHistory');

Route::get('/translation',  'AdminController@translation')->name('translation');

//History
Route::get('history', 'AdminController@history')->name('history');

//Privacy
Route::get('/privacy', 'AdminController@privacy')->name('privacy');
Route::get('/wallet', 'AdminController@adminwallet')->name('adminwallet');
Route::post('/pages', 'AdminController@pages')->name('pages.update');

//Terms
Route::get('/terms', 'AdminController@terms')->name('terms');
Route::post('/termspage', 'AdminController@termspages')->name('terms.update');
Route::post('/privacypages', 'AdminController@privacypages')->name('privacy.update');

Route::get('/about', 'AdminController@about')->name('about');
Route::post('/aboutpages', 'AdminController@aboutpages')->name('about.update');

//Promocode
Route::resource('promocode', 'PromocodeResource');

//Token
Route::resource('token', 'TokenResource');
Route::get('/token/document/{id}', 'TokenResource@viewdocument')->name('token.document');
Route::post('/token/status', 'TokenResource@status');

//Document Resource
Route::resource('document', 'DocumentResource');
Route::resource('corpdocument', 'CorpDocumentResource');

//AccreditedDocument Resource
Route::resource('accrediteddocument', 'AccreditedDocumentResource');

//ProspectusDocument Resource
Route::resource('prospectusdocument', 'ProspectusDocumentResource');

//Coins Resource
Route::resource('coin', 'CoinResource');
Route::get('coin/{id}/enableStatus', 'CoinResource@enableStatus')->name('coin.enableStatus');
Route::get('coin/{id}/disableStatus', 'CoinResource@disableStatus')->name('coin.disableStatus');

Route::get('user/{id}/kycdoc', 'AdminController@kycdoc')->name('user.kycdoc');
Route::post('userdocument/approve', 'AdminController@userdocument_approve')->name('userdocument.approve');
Route::post('userdocument/reject', 'AdminController@userdocument_reject')->name('userdocument.reject');

Route::get('user/{id}/accrediteddoc', 'AdminController@accrediteddoc')->name('user.accrediteddoc');
Route::post('useraccrediteddocument/approve', 'AdminController@useraccrediteddocument_approve')->name('useraccrediteddocument.approve');
Route::post('useraccrediteddocument/reject', 'AdminController@useraccrediteddocument_reject')->name('useraccrediteddocument.reject');

Route::get('user/{id}/approve', 'AdminController@approve')->name('user.approve');
Route::get('user/{id}/disapprove', 'AdminController@disapprove')->name('user.disapprove');

//withdraw

Route::get('pendingwithdraw', 'AdminController@pendingwithdraw')->name('pendingwithdraw');

Route::get('allwithdraw', 'AdminController@allwithdraw')->name('allwithdraw');


//cryptopendingwithdraw

Route::get('cryptopendingwithdraw', 'AdminController@cryptopendingwithdraw')->name('cryptopendingwithdraw');

Route::get('cryptoallwithdraw', 'AdminController@cryptoallwithdraw')->name('cryptoallwithdraw');



Route::get('history/success/{id}', 'AdminController@historySuccess')->name('history.success');

Route::get('history/failed/{id}', 'AdminController@historyFailed')->name('history.failed');

Route::get('coinwithdrawhistory/success/{id}', 'AdminController@coinwithdrawhistorySuccess')->name('coinwithdrawhistory.success');

Route::get('coinwithdrawhistory/failed/{id}', 'AdminController@coinwithdrawhistoryFailed')->name('coinwithdrawhistory.failed');


Route::get('receivehistory/success/{id}', 'AdminController@ReceivehistorySuccess')->name('receivehistory.success');

Route::get('receivehistory/failed/{id}', 'AdminController@ReceivehistoryFailed')->name('receivehistory.failed');

Route::post('addwireamount', 'AdminController@addwireamount')->name('addwireamount');
Route::get('removewireamount/{id}', 'AdminController@removewireamount')->name('removewireamount');

//Edit coin

Route::post('editcoin', 'AdminController@editcoin')->name('editcoin');

Route::post('savecoin', 'AdminController@savecoin')->name('savecoin');

Route::get('/btcotpgenerate/{ctype}', 'AdminController@btcotpgenerate')->name('btcotpgenerate');


Route::post('overallBTC', 'AdminController@overallBTC')->name('overallBTC');
Route::post('overallLTC', 'AdminController@overallLTC')->name('overallLTC');
Route::post('overallBCH', 'AdminController@overallBCH')->name('overallBCH');
Route::post('withdrawETH', 'AdminController@withdrawETH')->name('withdrawETH');

Route::any('withETH', 'AdminController@withdrawETH');

Route::get('/support','AdminController@support')->name('support');
//supportdone
Route::get('/supportdone/{id}/{status}','AdminController@supportdone')->name('supportdone');

Route::get('/addtoken','AdminController@addtoken')->name('addtoken');
//addtokendone
Route::get('/addtokendone/{id}','AdminController@addtokendone')->name('addtokendone');


//Sub Admin

Route::get('/listsubadmin', 'AdminController@listsubadmin')->name('listsubadmin');
Route::get('/createsubadmin', 'AdminController@createsubadmin')->name('createsubadmin');
Route::get('/editsubadmin/{id}', 'AdminController@editsubadmin')->name('editsubadmin');
Route::post('/storesubadmin', 'AdminController@storesubadmin')->name('storesubadmin');
Route::post('/updatesubadmin', 'AdminController@updatesubadmin')->name('updatesubadmin');
Route::delete('/destroysubadmin/{id}', 'AdminController@destroysubadmin')->name('destroysubadmin');

//sendmailforkycrejection
Route::get('sendmailforkycrejection', 'AdminController@sendmailforkycrejection')->name('sendmailforkycrejection');
Route::get('kycmail', 'AdminController@kycmail')->name('kycmail');

// Voting 
Route::resource('vote', 'VoteController');
Route::get('vote/status/{id}', 'VoteController@status')->name('admin.vote.status');

Route::get('voteresult/{id}', 'VoteController@voteresult')->name('vote.voteresult');


// Type of Funds
Route::get('/fund', 'InvestorController@indexfund')->name('fund');
Route::get('/createfund', 'InvestorController@createfund')->name('createfund');
Route::get('/editfund/{id}', 'InvestorController@editfund')->name('editfund');
Route::post('/storefund', 'InvestorController@storefund')->name('storefund');
Route::post('/updatefund', 'InvestorController@updatefund')->name('updatefund');

// Investor Types
Route::resource('investor', 'InvestorController');

// Worth Status
Route::get('/worthstatus', 'InvestorController@indexworthstatus')->name('worthstatus');
Route::get('/createworthstatus', 'InvestorController@createworthstatus')->name('createworthstatus');
Route::get('/editworthstatus/{id}', 'InvestorController@editworthstatus')->name('editworthstatus');
Route::post('/storeworthstatus', 'InvestorController@storeworthstatus')->name('storeworthstatus');
Route::post('/updateworthstatus', 'InvestorController@updateworthstatus')->name('updateworthstatus');


//Property
Route::resource('property','PropertyController');
Route::get('propertyFeature/{id}', 'PropertyController@propertyFeature');
Route::get('propertyTrusted/{id}', 'PropertyController@propertyTrusted');
Route::get('propertyEthereumAddress/{id}', 'PropertyController@propertyEthereumAddress');
Route::get('propertyGrowth/{id}', 'PropertyController@propertyGrowth');
Route::get('propertyOffice/{id}', 'PropertyController@propertyOffice');
Route::get('propertyGradea/{id}', 'PropertyController@propertyGradea');
Route::get('investstoreadmin/{id}', 'HomeController@investstoreadmin');
Route::post('propertyStatus/{id}', 'PropertyController@propertyStatus');
Route::get('property/show/assetType', 'PropertyController@ShowAssetType')->name('property.showasset');
//Delete Document
Route::post('propertydocumentdelete', 'PropertyController@documentdelete')->name('property.documentdelete');
Route::get('property/create/assetType', 'PropertyController@CreateAssetType')->name('property.createasset');
Route::post('property/store/assetType','PropertyController@storeAssetType')->name('property.storeasset');
Route::get('property/edit/assetType/{id}', 'PropertyController@showEdit')->name('property.editasset');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', 'AdminAuth\LoginController@showLoginForm')->name('adminlogin');
    Route::get('/issuer/login', 'AdminAuth\LoginController@showLoginIssuerForm')->name('adminIssuerlogin');
    Route::post('/login', 'AdminAuth\LoginController@login');
    Route::post('/logout', 'AdminAuth\LoginController@logout')->name('adminlogout');

    //Route::get('/issuer/register', 'AdminAuth\RegisterController@showIssuerRegistrationForm')->name('Issuerregister');
    //Route::post('/issuer/register', 'AdminAuth\RegisterController@register');

    Route::get('/register', 'AdminAuth\RegisterController@showRegistrationForm')->name('register');
    Route::post('/register', 'AdminAuth\RegisterController@register');


    Route::post('/password/email', 'AdminAuth\ForgotPasswordController@sendResetLinkEmail')->name('password.request');
    Route::post('/password/reset', 'AdminAuth\ResetPasswordController@reset')->name('password.email');
    Route::get('/password/reset', 'AdminAuth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
    Route::get('/password/reset/{token}', 'AdminAuth\ResetPasswordController@showResetForm');
});

Route::get('/issuer/login', 'Auth\LoginController@showLoginIssuerForm')->name('adminIssuerlogin');
Route::post('/issuer/login', 'AdminAuth\LoginController@login');

Route::get('/issuer/register', 'Auth\RegisterController@showIssuerRegistrationForm')->name('Issuerregister');
Route::post('/issuer/register', 'Auth\RegisterController@register_issuer');



Route::get('/', 'Auth\LoginController@welcome');
Route::post('getenquiryform', 'Auth\LoginController@getenquiryform')->name('getenquiryform');
Route::post('getenquiryformhome', 'HomeController@getenquiryformhome')->name('getenquiryformhome');
Route::get('/verifyemail/{token}', 'Auth\RegisterController@verify')->name('email_verify');

Route::get('forgot', function () {
    return view('forgot');
});

Route::get('/success', function () {
    return view('success');
});

Route::get('/wyre', 'WyreController@index');
Route::get('/wyretest', 'WyreController@wyretest');

Route::get('fiatpaymentstatus', 'WyreController@fiatpaymentstatus')->name('fiatpaymentstatus');

Auth::routes();

Route::get('/admin/dashboard', 'AdminDashboardController@index')->middleware('auth:admin');

Route::group(['middleware' => 'auth'], function () {
    // ********************** Investor ***********************
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'HomeController@investment')->name('dashboard');
    //Route::get('/propertyList', 'HomeController@propertyList')->name('propertyList');
    Route::get('/intel', 'HomeController@intel')->name('intel');
     Route::get('/help', 'HomeController@help')->name('help');
    Route::get('/profile', 'HomeController@profile')->name('profile');
    Route::get('/propertyDetail/{id}', 'HomeController@propertyDetail')->name('propertyDetail');
    Route::get('/applyInvest/{id}', 'HomeController@applyInvest')->name('applyInvest');
    Route::post('investstore', 'HomeController@investstore')->name('investstore');


    Route::get('walletBalanceAPI', 'HomeController@wallet_balance_api')->name('walletBalanceAPI');


    Route::get('security', 'UserController@security')->name('security');

    Route::post('/change/password', 'HomeController@update_password')->name('change.password');
    Route::get('participants', function () {
        return view('participants');
    });
    Route::get('prospectus', 'HomeController@prospectus');
    Route::post('prospectus_download', 'HomeController@prospectus_download')->name('prospectus_download');
    Route::get('kyc', 'HomeController@kyc');
    Route::post('personalinfo', 'HomeController@personalinfo');
    Route::post('userdetail', 'HomeController@userdetail')->name('userdetail');
    Route::post('kycstore', 'HomeController@kycstore');
    Route::post('accrediteduserstore', 'HomeController@accrediteduserstore');
    Route::post('accreditedkycstore', 'HomeController@accreditedkycstore');
    Route::post('usercompanydetail', 'HomeController@usercompanydetail')->name('usercompanydetail');
    Route::post('usercompanypersonaldetail', 'HomeController@usercompanypersonaldetail')->name('usercompanypersonaldetail');
    Route::get('wallet', 'HomeController@wallet')->name('wallet');
    Route::get('payment_history', 'HomeController@paymenthistory')->name('paymenthistory');
    Route::get('withdrawETH', 'HomeController@withdrawETHBalance')->name('withdrawETH');
    Route::post('/sendETH', 'HomeController@sendETH')->name('sendETH');
    Route::get('/generate/withdrawOTP', 'HomeController@generateWithdrawOTP')->name('generateWithdrawOTP');
    Route::post('privateKeyPassword', 'HomeController@privateKeyPassword')->name('privateKeyPassword');
    Route::get('privateKeyShow/{id}', 'HomeController@privateKeyShow')->name('privateKeyShow');
    Route::post('requestaddress', 'HomeController@requestaddress')->name('requestaddress');
    Route::post('addtoken', 'HomeController@addtoken')->name('addtoken');
    Route::post('withdraw', 'HomeController@withdraw')->name('withdraw');
    Route::post('storePayment', 'HomeController@storePayment');

    Route::get('balance', 'HomeController@balance_of_coin')->name('balance');
    Route::post('getcryptobalance', 'HomeController@getcryptobalance')->name('getcryptobalance');
    Route::post('gettokeninvestvalue', 'HomeController@gettokeninvestvalue')->name('gettokeninvestvalue');
    

    // ---------------- Invest --------------------
    Route::get('invest_token/{id}', 'HomeController@invest_token')->name('invest_token');
    Route::post('investstore', 'HomeController@investstore')->name('investstore');
    //Route::get('fiatpaymentstatus', 'HomeController@fiatpaymentstatus')->name('fiatpaymentstatus');
    // ---------------- Invest -------------------  -

    Route::get('dividend', 'HomeController@dividend');
    Route::get('voting', 'HomeController@showvoting');
    Route::post('votingstore', 'HomeController@votingstore')->name('votingstore');
    Route::get('support', function () {
        return view('support');
    });
    Route::post('supportstore', 'HomeController@supportstore')->name('supportstore');

    Route::get('privacy-policy', function () {
        return view('privacy-policy');
    });
    Route::get('terms-use', function () {
        return view('terms-use');
    });
    // ********************** Investor ***********************

    //Google 2 factor
    Route::get('g2fenablesuccess/{id}', 'UserController@g2fenablesuccess')->name('g2fenablesuccess');
    Route::get('/2fa/enable', 'Google2FAController@enableTwoFactor');
    Route::get('/2fa/disable', 'Google2FAController@disableTwoFactor')->name('disableTwoFactor');;
    // Web check otp
    Route::post('/g2fotpcheckenable', 'Google2FAController@g2fotpcheckenable');

});

Route::get('/2fa/validate', 'Auth\LoginController@getValidateToken');
Route::post('/2fa/validate', ['middleware' => 'throttle:5', 'uses' => 'Auth\LoginController@postValidateToken']);

// API check otp
//Route::post('/gfaenablereal', 'Google2FAController@postValidateToken');
Route::post('/gfavalidateotp', 'Google2FAController@gfavalidateotp');


/*Route Real Estate STO*/

Route::get('/privacy', function(){ return view('privacy');});
Route::get('/terms_conditions', function(){ return view('terms_conditions');});

Route::get('/blog', 'HomeController@blog')->name('blog');
Route::get('/blogDetail', 'HomeController@blogDetail')->name('blogDetail'); //Dynami
//Route::get('/wallet', 'HomeController@wallet')->name('wallet');
Route::get('/investment', 'HomeController@investment')->name('investment');
Route::get('/investDetail', 'HomeController@investDetail')->name('investDetail');
Route::get('/setting', 'HomeController@setting')->name('setting');
Route::get('/activity', 'HomeController@activity')->name('activity');
Route::get('/sellToken', 'HomeController@sellToken')->name('sellToken');
Route::get('/buyToken', 'HomeController@buyToken')->name('buyToken');
Route::post('/profile-identity', 'HomeController@profile_identity')->name('profile.identity');
Route::post('/phelp', 'HomeController@phelp')->name('phelp');
Route::post('/profile-finance', 'HomeController@profile_finance')->name('profile.finance');
Route::post('/profile-background', 'HomeController@profile_background')->name('profile.background');
Route::get('/propertyList', 'HomeController@propertyList')->name('propertyList');

Route::get('/under_construction', function () {
    return view('under_construction');
}
);

Route::get('/propertyList/{type?}', 'HomeController@propertyList')->name('propertyList');
Route::get('/property-asset-list/{type}', 'HomeController@propertyAssetList')->name('propertyAssetList');


Route::get('/propertyDetail/{id}', 'HomeController@propertyDetail')->name('propertyDetail'); // Dynamic

Route::get('/countrycity/{country}', 'UserController@countrycity')->name('countrycity');
Route::group(['prefix' => 'issuer', 'middleware' => 'auth'], function () {
    Route::get('/dashboard', 'IssuerController@dashboard')->name('dashboard');
    Route::get('/kyc', 'IssuerController@kyc')->name('kyc');
    Route::post('/kyc', 'IssuerController@updateKyc')->name('updateKyc');
     Route::post('/updateBankDetails', 'IssuerController@updateBankDetails')->name('updateBankDetails');
    Route::get('/profile', 'IssuerController@profile')->name('profile');
    Route::post('/profile_update', 'IssuerController@profile_update')->name('profile_update');

resources/views/admin/prospectusdocument/create.blade.php
@extends('admin.layout.base')

@section('title', 'Add Document ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
        <div class="box box-block bg-white">
            <a href="{{ route('admin.prospectusdocument.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> @lang('admin.back') </a>

            <h5 style="margin-bottom: 2em;">@lang('admin.add_doc')</h5>

            <form class="form-horizontal" action="{{route('admin.prospectusdocument.store')}}" method="POST" enctype="multipart/form-data" role="form">
                {{csrf_field()}}
                <div class="form-group row">
                    <label for="name" class="col-xs-12 col-form-label">@lang('admin.doc_name')</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="text" value="{{ old('name') }}" name="title" required id="title" placeholder="@lang('admin.doc_name')">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="order" class="col-xs-12 col-form-label">@lang('admin.doc_order')</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="number" value="{{ old('order') }}" order="order" required id="order" placeholder="@lang('admin.doc_order')" name="order">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="image" class="col-xs-12 col-form-label">@lang('admin.doc_file') </label>
                    <div class="col-xs-10">                        
                        <input type="file" name="document" class="dropify form-control-file" id="document" aria-describedby="fileHelp">
                    </div>
                </div>        

                <div class="form-group row">
                    <label class="col-xs-12 col-form-label"></label>
                    <div class="col-xs-10">
                        <button type="submit" class="btn btn-primary">@lang('admin.add_doc')</button>
                        <a href="{{route('admin.prospectusdocument.index')}}" class="btn btn-default">@lang('admin.cancel')</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

@endsection

resources/views/admin/prospectusdocument/edit.blade.php
@extends('admin.layout.base')

@section('title', 'Update Document ')

@section('content')

<div class="content-area py-1">
    <div class="container-fluid">
    	<div class="box box-block bg-white">
    	    <a href="{{ route('admin.prospectusdocument.index') }}" class="btn btn-default pull-right"><i class="fa fa-angle-left"></i> @lang('admin.back')</a>

			<h5 style="margin-bottom: 2em;">@lang('admin.update_doc')</h5>

            <form class="form-horizontal" action="{{route('admin.prospectusdocument.update', $document->id )}}" method="POST" enctype="multipart/form-data" role="form">
            	{{csrf_field()}}
            	<input type="hidden" name="_method" value="PATCH">
				<div class="form-group row">
					<label for="name" class="col-xs-2 col-form-label">@lang('admin.doc_name')</label>
					<div class="col-xs-10">
						<input class="form-control" type="text" value="{{ $document->title }}" name="title" required id="title" placeholder="Document Name">
					</div>
				</div>

				  <div class="form-group row">
                    <label for="order" class="col-xs-2 col-form-label">@lang('admin.doc_order')</label>
                    <div class="col-xs-10">
                        <input class="form-control" type="number" value="{{ $document->order }}" order="order" required id="order" placeholder="Document order" name="order">
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="image" class="col-xs-2 col-form-label">@lang('admin.doc_file')</label>
                    <div class="col-xs-10">

                    	@if($document->document !='')
	                    <a href="{{ img($document->document) }}" >Download</a>
	                    @endif
                        
                        <input type="file"  name="document" class="dropify form-control-file" id="document" aria-describedby="fileHelp" value="{{ $document->document }}">
                    </div>
                </div>

				<div class="form-group row">
					<label class="col-xs-2 col-form-label"></label>
					<div class="col-xs-10">
						<button type="submit" class="btn btn-primary">@lang('admin.update_doc')</button>
						<a href="{{route('admin.prospectusdocument.index')}}" class="btn btn-default">@lang('admin.cancel')</a>
					</div>
				</div>
			</form>
		</div>
    </div>
</div>

@endsection

resources/views/admin/prospectusdocument/index.blade.php
@extends('admin.layout.base')

@section('title', 'Documents ')

@section('content')

    <div class="content-area py-1">
        <div class="container-fluid">
            
            <div class="box box-block bg-white">
           
                <h5 class="mb-1">@lang('admin.documents')</h5>
                <a href="{{ route('admin.prospectusdocument.create') }}" style="margin-left: 1em;" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> @lang('admin.add_doc')</a>
                <table class="table table-striped table-bordered dataTable" id="table-2">
                    <thead>
                        <tr>
                            <th>@lang('admin.id')</th>
                            <th>@lang('admin.doc_name')</th>
                            <th>@lang('user.action')</th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($documents as $index => $document)
                        <tr>
                            <td>{{$index + 1}}</td>
                            <td>{{$document->title}}</td>
                            <td>
                                <form action="{{ route('admin.prospectusdocument.destroy', $document->id) }}" method="POST">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    @if( Setting::get('demo_mode') == 0)
                                    <a href="{{ route('admin.prospectusdocument.edit', $document->id) }}" class="btn btn-info"><i class="fa fa-pencil"></i> @lang('admin.edit')</a>
                                    <button class="btn btn-danger" onclick="return confirm('Are you sure?')"><i class="fa fa-trash"></i>@lang('admin.delete')</button>
                                    @endif
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                    <tfoot>
                        <tr>
                            <th>@lang('admin.id')</th>
                            <th>@lang('admin.doc_name')</th>
                            <th>@lang('user.action')</th>
                        </tr>
                    </tfoot>
                </table>
            </div>
            
        </div>
    </div>
@endsection